# Generated by Django 3.1.5 on 2021-01-18 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interstellar', '0002_auto_20210118_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='constellations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='coordinatesX',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='coordinatesY',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='date_hour_product',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
