# Generated by Django 3.1.5 on 2021-01-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interstellar', '0003_auto_20210118_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_hour_product',
            field=models.DateTimeField(default=None),
        ),
    ]
